Improve BHoM Analytics Pop Up Window
BHoM/BHoMAnalytics_Toolkit pull request #38
Opened 2022-09-09 14:04 UTC by travispotterBH

New PR for branch name compliance: https://github.com/BHoM/BHoMAnalytics_Toolkit/pull/37

### Issues addressed by this PR

Closes #36

Added Branding:
![image](https://user-images.githubusercontent.com/96432552/189193307-aa8c8676-287d-4c81-929b-73c4894ac862.png)
@FraserGreenroyd  I need help knowing where the image should be placed, and referenced. Will need to ship with installer. 
Image below:
![BHoM_Logo](https://user-images.githubusercontent.com/96432552/189193506-278c1526-49bc-474c-847e-64600728e030.png)

Added custom UI for Revit:
![BhomAnalytics - Revit version](https://user-images.githubusercontent.com/96432552/189192836-56574777-1cb3-479f-881a-8e098f14d45b.gif)

Revit Self Assign Project Number, when Project Information is set:
![BhomAnalytics - Revit Self Assign Project Number](https://user-images.githubusercontent.com/96432552/189192928-63bc8ca3-257f-442e-b053-00ed330b76cc.gif)

Revit User Assign Project Number, when Project Information is not set:
![BhomAnalytics - Revit user Assign Project Number](https://user-images.githubusercontent.com/96432552/189192973-6157b33c-37fe-40c0-9943-362ea90aabb9.gif)

Added custom UI for Grasshopper:
![BhomAnalytics - Grasshopper version](https://user-images.githubusercontent.com/96432552/189192848-a1916303-86ae-47c3-b85a-bb451b2b4e00.gif)

### Changelog

- Improved UX by modifying per UI
- Allows movable window
- Includes additional options for non project work
- Improves UI by including branding

### Additional comments

@FraserGreenroyd @al-fisher requested modifications to the installer to update information about logging. 
![image](https://user-images.githubusercontent.com/96432552/189194119-d0885cd0-d173-4d47-bb14-f592c9ebd539.png)

2022-09-09 15:18 UTC, FraserGreenroyd requested changes

2022-09-09 15:18 UTC, FraserGreenroyd commented on BHoMAnalytics_UI/CaptureProjectData.xaml.cs
> +            if (_uiName == "Revit")
```suggestion
            }
            else if (_uiName == "Revit")
```

2022-09-09 15:18 UTC, FraserGreenroyd commented on BHoMAnalytics_UI/CaptureProjectData.xaml.cs
> +            if (_uiName == "Excel")
```suggestion
            }
            else if (_uiName == "Excel")
```

2022-09-09 15:18 UTC, FraserGreenroyd commented on BHoMAnalytics_UI/CaptureProjectData.xaml.cs
> +
```suggestion
```

2022-09-09 15:18 UTC, FraserGreenroyd commented on BHoMAnalytics_UI/CaptureProjectData.xaml.cs
> +            this._uiName = uiName;
```suggestion
            _uiName = uiName;
```

2022-09-09 15:18 UTC, FraserGreenroyd commented on BHoMAnalytics_UI/CaptureProjectData.xaml.cs
> +        private void KeyDown_ProjectIDEntry(object sender, KeyEventArgs e)
```suggestion

        private void Click_ConfirmProjectBtn(object sender, EventArgs e)
        {
            ConfirmProject();
        }
        
        private void KeyDown_ProjectIDEntry(object sender, KeyEventArgs e)
```

2022-09-09 15:18 UTC, FraserGreenroyd commented on BHoMAnalytics_UI/CaptureProjectData.xaml.cs
> +            if ((NonProjectSelectionPanel.Visibility == Visibility.Visible && OtherSpecifyInput.Visibility == Visibility.Visible) && string.IsNullOrEmpty(OtherSpecifyInput.Text))
I would move this check to be above the building of the `projectID` variable above

2022-09-09 15:18 UTC, FraserGreenroyd commented on BHoMAnalytics_UI/CaptureProjectData.xaml.cs
> +            //Grasshopper specific
Is this still just Grasshopper now?

2022-09-09 15:18 UTC, FraserGreenroyd commented on BHoMAnalytics_oM/Enums/NonProjectOption.cs
> +
```suggestion
```

2022-09-09 15:18 UTC, FraserGreenroyd commented on BHoMAnalytics_oM/Enums/NonProjectOption.cs
> +        Development = 5,
Tagging @alexissantella back in to confirm if they're happy with this, or would be better with integer increments and we add them in alphabetically but start at 1 and count up from there

2022-09-09 16:29 UTC, FraserGreenroyd approved these changes
Code review looks good, happy to merge if @alexissantella is happy with the enum.

2022-09-12 14:07 UTC, FraserGreenroyd requested changes

2022-09-12 14:07 UTC, FraserGreenroyd commented on BHoMAnalytics_oM/Enums/NonProjectOption.cs
> +        Other = 20
```suggestion
        Development = 1,
        Testing = 2,
        Training = 3,
        Hackademy = 4,
        Other = 5,
```

Discussed with @alexissantella on a call - this is the desired input for non-project workflows number wise, and adding the addition of `Training` as a discrete option to `Hackademy`.

2022-09-12 14:10 UTC, FraserGreenroyd commented
@BHoMBot check versioning
@BHoMBot check installer

2022-09-12 16:33 UTC, FraserGreenroyd commented
@BHoMBot check required

2022-09-12 17:49 UTC, travispotterBH commented
@BHoMBot copyright-compliance

2022-09-12 18:06 UTC, travispotterBH commented
@BHoMBot  check copyright-compliance

2022-09-12 18:18 UTC, FraserGreenroyd approved these changes
Code reviewed following call with Alexis happy to merge.

2022-09-12 18:19 UTC, FraserGreenroyd commented
@BHoMBot check ready-to-merge

2022-09-12 18:41 UTC, merged